#!/bin/csh
#
set REM2D=.
#
$REM2D/rem2d_demtr0.x << EOF
1
EOF
mv FNA xsect1.p
#
$REM2D/rem2d_demtr0.x << EOF
2
EOF
mv FNA xsect2.p
#
$REM2D/rem2d_demtr0.x << EOF
3
EOF
mv FNA xsect3.p
#
$REM2D/rem2d_demtr0.x << EOF
4
EOF
mv FNA xsect4.p
#
