#!/bin/csh
#
set W = 4
set H = 4
set AC = white
set TS = 15
set t = "300 ms"

suaddhead < xzsnap.p ns=125 ftn=1 | \
supsimage width=$W height=$H axescolor=$AC titlesize=$TS \
          title="Pressure     t=$t" clip=1e-10 \
          > sn_pnt_s_p.ps

suaddhead < xzsnap.s ns=125 ftn=1 | \
supsimage width=$W height=$H axescolor=$AC titlesize=$TS \
          title="Shear     t=$t" clip=1.e-9 \
          > sn_pnt_s_s.ps

suaddhead < xzsnap.ux ns=125 ftn=1 | \
supsimage width=$W height=$H axescolor=$AC titlesize=$TS \
          title="x-Displacement     t=$t" clip=5.e-9 \
          > sn_pnt_s_ux.ps

suaddhead < xzsnap.uz ns=125 ftn=1 | \
supsimage width=$W height=$H axescolor=$AC titlesize=$TS \
          title="z-Displacement     t=$t" clip=5.e-9 \
          > sn_pnt_s_uz.ps

